# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOCKER_HUB_USERNAME: baladocker1729
  DOCKER_HUB_PASSWORD: BalaDocker@123

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build and package project
        run: mvn clean install

      - name: Log in to Docker Hub
        run: echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t $DOCKER_HUB_USERNAME/bala-own-image:latest .
          docker push $DOCKER_HUB_USERNAME/bala-own-image:latest
#          docker build -t $DOCKER_HUB_USERNAME/bala-own-image:${{ github.sha }} .
#          docker push $DOCKER_HUB_USERNAME/bala-own-image:${{ github.sha }}

#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v3
#    - name: Set up JDK 17
#      uses: actions/setup-java@v3
#      with:
#        java-version: '17'
#        distribution: 'temurin'
#        cache: maven
#    - name: Build with Maven
#      working-directory: .
#      run: mvn clean install
#
#    - uses: actions/checkout@v3
#      name: Check out code
#
#    - uses: mr-smithers-excellent/docker-build-push@v6
#      name: Build & push Docker image
#      with:
#        image: baladocker1729/image
#        tags: latest
#        registry: docker.io
#        dockerfile: Dockerfile
#        username: baladocker1729
#        password: BalaDocker@123

